version: "3.1"
secrets:
  twilio-credentials:
    file: ./secrets/twilio-credentials.json
services:
  app:
    image: node:8
    container_name: app
    command: [yarn, start]
    working_dir: /usr/src/app
    secrets:
      - twilio-credentials
    volumes:
        - .:/usr/src/app
    ports:
      - "1337:1337"

