version: "3.1"
secrets:
  tls-key:
    file: ./secrets/tls/dev/self-signed.key
  tls-cert:
    file: ./secrets/tls/dev/self-signed.crt
  tls-dhparam:
    file: ./secrets/tls/dev/dhparam.pem
  twilio-credentials:
    file: ./secrets/twilio-credentials.json
  google-sign-in-app-credentials:
    file: ./secrets/google-sign-in-app-credentials.json
services:
  app:
    image: nginx
    container_name: app-proxy
    depends_on:
      - app-core
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    secrets:
      - tls-key
      - tls-cert
      - tls-dhparam
    ports:
      - "443:443"
      - "80:80"
  app-core:
    image: node:8
    container_name: app-core
    command: [yarn, start]
    working_dir: /usr/src/app
    secrets:
      - twilio-credentials
      - google-sign-in-app-credentials
    networks:
      - app
    volumes:
        - .:/usr/src/app
    environment:
      PORT: 80
      NODE_ENV: "development"
      TWILIO_ENABLED_NUMBER: '+13156276319'
      TWILIO_WEBHOOK_API_URL_BASE: 'https://auto-connect.ngrok.io/'
networks:
  app:
